
##### RESOURCES #####
mem: '32000'
threads: 2

##### GENERAL #####
project_name: RNAhom
result_path: /nobackup/lab_bock/projects/JakStruct/results/RNAhom/
annotation: config/RNAhom_rnaseq_pipeline_annotation.csv

##### PROCESSING #####

trimming:
  # If you activate trimming by setting this to `True`, you will have to
  # specify the respective cutadapt adapter trimming flag for each unit
  # in the `units.tsv` file's `adapters` column
  activate: False

params:
  cutadapt-pe: ""
  cutadapt-se: ""
  star: ""

##### RESOURCES #####

ref:
  # Ensembl species name
  species: homo_sapiens
  # Ensembl release (make sure to take one where snpeff data is available, check 'snpEff databases' output)
  release: 100
  # Genome build
  build: GRCh38


